### ISSUE TITLE
xPlayer

### ISSUE THREAD

**Issue by fivemroli** [Sarmingo/sarmingo-registrationsystem#3]
hi Sarmingo
plz help, my problem:::  [script:sarmingo-regi] SCRIPT ERROR: @sarmingo-registrationsystem/server/main.lua:23: attempt to index a nil value (local 'xPlayer')

**Comment by Sarmingo** [comment]
join my discord to i can help you

**Comment by fivemroli** [comment]
ok, discord link?

**Comment by zodiak-dev** [comment]
whats the discord link please
