### ISSUE TITLE
console 

### ISSUE THREAD

**Issue by valvi1** [Sarmingo/sarmingo-registrationsystem#4]
![image](https://github.com/Sarmingo/sarmingo-registrationsystem/assets/136049869/71cbacfb-3170-4b4a-8c72-af6fbfaf83af)
good I get this in the console several times

**Comment by Sarmingo** [comment]
this is not error remove print from server side or client

**Comment by valvi1** [comment]
> this is not error remove print from server side or client

another thing i have also noticed that when i take the car out of the garage an npc appears inside and takes the car when the scrip is active. it's weird. it's happened to me 3/10.
